### ISSUE TITLE
Not working now

### ISSUE THREAD

**Issue by nlboom** [recallfuture/FurryDownloader#4] opened 2020-09-19 18:18 UTC
Hi. The program does not downloading images, the save folder is empty.
[log.txt](https://github.com/recallfuture/FurryDownloader/files/5250388/log.txt)

![5665566554544545](https://user-images.githubusercontent.com/15813558/93686248-ac9db100-fabd-11ea-86a2-4e4b675ce134.png)

**Comment by recallfuture** [comment] 2020-09-20 15:41
Hi, it's fixed on 5.4.1, checkout new release!

This bug is caused by Furaffinity banning HTTP access, so I fixed all picture url with HTTPS! But there still have something to do by your self, you need check the option which added this time, bescuse program cached http pic url before.  That option will ignore exist cache file and relpase it with new url.

hmmm, maybe delete all cache files is better, They're on C:\Users\yourname\Documents\FaDownloader\cache

Hope you have a good time!

**Closed as completed by recallfuture** 2020-09-20 15:41 UTC
